---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: blueniri
# description will be included in the image's metadata
description: This is my personal niri OS image.

# the base image to build on top of (FROM) and the version tag to use
#base-image: quay.io/fedora-ostree-desktops/base-atomic
base-image: quay.io/fedora/fedora-bootc
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:

  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - from-file: common/justfiles-modules.yml
  - from-file: common/chezmoi-modules.yml
  - from-file: common/flatpaks-modules.yml
  - from-file: common/fonts-modules.yml
  - from-file: common/script-modules.yml
  #- from-file: common/netbird-modules.yml
  - from-file: common/virtualisation-modules.yml
  - from-file: common/hw-modules.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

